{{- if .Values.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "event-consumer.fullname" .}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "event-consumer.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "event-consumer.fullname" .}}
  port:
    targetPort: http
{{- if .Values.route.tls }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
  wildcardPolicy: None
{{- end }}
